### ISSUE TITLE
[enterprise-4.4] Issue in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by lautou** [openshift/openshift-docs#23148]
### Which section(s) is the issue in?
Creating Red Hat Enterprise Linux CoreOS (RHCOS) machines in vSphere

### What needs fixing?
According to the § **Creating the user-provisioned infrastructure** is is stated :
_Configure DHCP or set static IP addresses on each node._
There is no explanation how to set static IP addresses using OVA method here.
Note it is explained in bare-metal installation page (both for ISO and PXE/iPXE).
Does it mean that we have to use bare-metal installation method if choosing to set static IP instead using OVA method?

**Comment by lautou** [comment]
hi any update

**Comment by rarguello** [comment]
Fixed in #25846

**Comment by lautou** [comment]
> Fixed in #25846
Yeak but doc is still not update
https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere.html

**Comment by codyhoag** [comment]
This was addressed in #27394
