### ISSUE TITLE
[enterprise-4.11] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by mauroseb** [openshift/openshift-docs#51419]
### Which section(s) is the issue in?
Installing the logging subsystem for Red Hat OpenShift using the CLI 
(step) 3. Install the OpenShift Elasticsearch Operator by creating the following objects 

### What needs fixing?
The example subscription for Elasticsearch operator is in still pointintg to stable-5.1 channel.
It should read stable-5.4

**Comment by cbremble** [comment]
I believe this was fixed with https://issues.redhat.com/browse/RHDEVDOCS-4405. @libander can you confirm? The example refers to 5.1 but the actual instructions explain further.

**Comment by mauroseb** [comment]
Hi @cbremble, 

I still see stable-5.1 in the docs:
https://docs.openshift.com/container-platform/4.11/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying
CLI Deployment, Step 3.c.

Also "stable" should work as indicated in the note following the example with 5.1.

**Comment by cbremble** [comment]
Added to Jira: [RHDEVDOCS-4791](https://issues.redhat.com/browse/RHDEVDOCS-4791)

**Comment by abrennan89** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/67450
