### ISSUE TITLE
[OKD] Incorrect link

### ISSUE THREAD

**Issue by jele84** [openshift/openshift-docs#96704]
There is a link at the end of the page https://docs.okd.io/latest/disconnected/mirroring/about-installing-oc-mirror-v2.html called [Updating a cluster in a disconnected environment using the OpenShift Update Service](https://docs.okd.io/latest/disconnected/updating/disconnected-update-osus.html#updating-disconnected-cluster-osus)

This link doesn't work. 

MBurke:
4.17: The about-installing-oc-mirror-v2.adoc file is at: https://docs.okd.io/4.17/disconnected/mirroring/about-installing-oc-mirror-v2.html
4.18+: The about-installing-oc-mirror-v2.adoc file was moved up one level in 4.18.  It is now: https://docs.okd.io/latest/disconnected/about-installing-oc-mirror-v2.html

**Comment by mburke5678** [comment]
https://github.com/openshift/openshift-docs/pull/97086

**Comment by ctomasko** [comment]
Fixed, please close

**Comment by mburke5678** [comment]
@ctomasko I am still seeing two links to this section in the OKD docs. I asked @skopacz1 if he can fix them in his PR.

**Comment by ctomasko** [comment]
Thanks. That content is in the agent installer section and Seb is the correct contact.

**Comment by mburke5678** [comment]
@Abhijais4896 I didn't see your comment until now. Did you pull a PR yet? If not, [how does this fix look](https://github.com/openshift/openshift-docs/pull/105714)? I changed the link from the Updating using OSUS to Updating using the CLI.
